version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest-debian
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: |
            hadolint Dockerfile
  test-app:
    docker:
      - image: golang:1.15-alpine
    steps:
      - checkout
      - run:
          name: Install gcc
          command: |
            apk update && apk add gcc
      - run:
          name: Install musl-dev
          command: |
            apk add musl-dev
      - run:
          name: Install Go
          command: |
            wget https://go.dev/dl/go1.15rc1.linux-amd64.tar.gz
            mkdir -p /usr/local/bin/go
            tar -xf go1.15rc1.linux-amd64.tar.gz -C /usr/local/bin/go
            export PATH=/usr/local/bin/go
      - run:
          name: Test app
          command: |
            go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push application Docker image
          command: |
            docker build -t ghcr.io/stevensa1/karsajobs:latest .
            echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
            docker push ghcr.io/stevensa1/karsajobs:latest

workflows:
  karsajobs-workflow:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs