version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: golang:1.15-alpine
    steps:
      - checkout
      - run:
          name: Install hadolint locally
          command: |
            wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            chmod +x hadolint-Linux-x86_64
            mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run:
          name: Lint Dockerfile
          command: |
            hadolint Dockerfile
  test-app:
    docker:
      - image: golang:1.15-alpine
    steps:
      - checkout
      - run:
          name: Install curl
          command: |
            apk update && apk add curl
      - run:
          name: Debug Directory
          command: |
            mkdir -p $PWD/go
      - run:
          name: Install Go
          command: |
            curl -Ls https://go.dev/dl/go1.15rc1.linux-amd64.tar.gz | tar -xf go1.15rc1.linux-amd64.tar.gz -C $PWD/go
            export GOPATH=$PWD/go
            export PATH=$GOPATH/bin:$PATH
      - run:
          name: Test app
          command: |
            go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    docker:
      - image: golang:1.15-alpine
    steps:
      - checkout
      - run:
          name: Build app
          command: |
            go build -o karsajobs
      - run:
          name: Debug Directory
          command: |
            dir
      - run:
          name: Push image
          command: |
            docker build -t ghcr.io/stevensa1/karsajobs:latest .
            docker push ghcr.io/stevensa1/karsajobs:latest

workflows:
  karsajobs-workflow:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs